### ISSUE TITLE
Update to latest ZT version

### ISSUE THREAD

**Issue by ropeguru** [dangeroustech/ZeroTierBridge#9]
WOuld it be possible to update to the lates ZT code version, 1.10.2??

Is this even still being maintained?

**Comment by biodrone** [comment]
Not sure why this didn't notify me when you commented, will update this today as I'm looking to actively maintain this project again.

**Comment by biodrone** [comment]
You can just specify the version you want in the docker-compose.yml file and it'll trickle that down to the Dockerfile when it's built, but I'll update the defaults anyway
